/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SenhaAlteradaRouteImport } from './routes/senha-alterada'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedConexoesRouteImport } from './routes/_authenticated/conexoes'
import { Route as AuthenticatedFixasRouteImport } from './routes/_authenticated/fixas'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTransacoesRouteImport } from './routes/_authenticated/transacoes'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedCartoesIndexRouteImport } from './routes/_authenticated/cartoes.index'
import { Route as AuthenticatedCartoesNovoRouteImport } from './routes/_authenticated/cartoes.novo'
import { Route as AuthenticatedCategoriasIndexRouteImport } from './routes/_authenticated/categorias.index'
import { Route as AuthenticatedCategoriasNovaRouteImport } from './routes/_authenticated/categorias.nova'
import { Route as AuthenticatedFixasIndexRouteImport } from './routes/_authenticated/fixas.index'
import { Route as AuthenticatedFixasNovaRouteImport } from './routes/_authenticated/fixas.nova'
import { Route as AuthenticatedMetasIndexRouteImport } from './routes/_authenticated/metas.index'
import { Route as AuthenticatedMetasNovaRouteImport } from './routes/_authenticated/metas.nova'
import { Route as AuthenticatedTransacoesIndexRouteImport } from './routes/_authenticated/transacoes.index'
import { Route as AuthenticatedTransacoesNovoRouteImport } from './routes/_authenticated/transacoes.novo'
import { Route as AuthenticatedCartoesIdEditarRouteImport } from './routes/_authenticated/cartoes.$id.editar'
import { Route as AuthenticatedCategoriasIdEditarRouteImport } from './routes/_authenticated/categorias.$id.editar'
import { Route as AuthenticatedFixasIdEditarRouteImport } from './routes/_authenticated/fixas.$id.editar'
import { Route as AuthenticatedMetasIdEditarRouteImport } from './routes/_authenticated/metas.$id.editar'
import { Route as AuthenticatedTransacoesIdEditarRouteImport } from './routes/_authenticated/transacoes.$id.editar'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SenhaAlteradaRoute = SenhaAlteradaRouteImport.update({
  id: '/senha-alterada',
  path: '/senha-alterada',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConexoesRoute = AuthenticatedConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFixasRoute = AuthenticatedFixasRouteImport.update({
  id: '/fixas',
  path: '/fixas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransacoesRoute = AuthenticatedTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartoesIndexRoute =
  AuthenticatedCartoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCartoesRoute,
  } as any)
const AuthenticatedCartoesNovoRoute =
  AuthenticatedCartoesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedCartoesRoute,
  } as any)
const AuthenticatedCategoriasIndexRoute =
  AuthenticatedCategoriasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCategoriasRoute,
  } as any)
const AuthenticatedCategoriasNovaRoute =
  AuthenticatedCategoriasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedCategoriasRoute,
  } as any)
const AuthenticatedFixasIndexRoute = AuthenticatedFixasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFixasRoute,
} as any)
const AuthenticatedFixasNovaRoute = AuthenticatedFixasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedFixasRoute,
} as any)
const AuthenticatedMetasIndexRoute = AuthenticatedMetasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMetasRoute,
} as any)
const AuthenticatedMetasNovaRoute = AuthenticatedMetasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedMetasRoute,
} as any)
const AuthenticatedTransacoesIndexRoute =
  AuthenticatedTransacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransacoesRoute,
  } as any)
const AuthenticatedTransacoesNovoRoute =
  AuthenticatedTransacoesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedTransacoesRoute,
  } as any)
const AuthenticatedCartoesIdEditarRoute =
  AuthenticatedCartoesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedCartoesRoute,
  } as any)
const AuthenticatedCategoriasIdEditarRoute =
  AuthenticatedCategoriasIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedCategoriasRoute,
  } as any)
const AuthenticatedFixasIdEditarRoute =
  AuthenticatedFixasIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedFixasRoute,
  } as any)
const AuthenticatedMetasIdEditarRoute =
  AuthenticatedMetasIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedMetasRoute,
  } as any)
const AuthenticatedTransacoesIdEditarRoute =
  AuthenticatedTransacoesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedTransacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/senha-alterada': typeof SenhaAlteradaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cartoes': typeof AuthenticatedCartoesRouteWithChildren
  '/categorias': typeof AuthenticatedCategoriasRouteWithChildren
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/fixas': typeof AuthenticatedFixasRouteWithChildren
  '/importar': typeof AuthenticatedImportarRoute
  '/metas': typeof AuthenticatedMetasRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/transacoes': typeof AuthenticatedTransacoesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/cartoes/novo': typeof AuthenticatedCartoesNovoRoute
  '/categorias/nova': typeof AuthenticatedCategoriasNovaRoute
  '/fixas/nova': typeof AuthenticatedFixasNovaRoute
  '/metas/nova': typeof AuthenticatedMetasNovaRoute
  '/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/cartoes/': typeof AuthenticatedCartoesIndexRoute
  '/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/fixas/': typeof AuthenticatedFixasIndexRoute
  '/metas/': typeof AuthenticatedMetasIndexRoute
  '/transacoes/': typeof AuthenticatedTransacoesIndexRoute
  '/cartoes/$id/editar': typeof AuthenticatedCartoesIdEditarRoute
  '/categorias/$id/editar': typeof AuthenticatedCategoriasIdEditarRoute
  '/fixas/$id/editar': typeof AuthenticatedFixasIdEditarRoute
  '/metas/$id/editar': typeof AuthenticatedMetasIdEditarRoute
  '/transacoes/$id/editar': typeof AuthenticatedTransacoesIdEditarRoute
}
export interface FileRoutesByTo {
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/senha-alterada': typeof SenhaAlteradaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/cartoes/novo': typeof AuthenticatedCartoesNovoRoute
  '/categorias/nova': typeof AuthenticatedCategoriasNovaRoute
  '/fixas/nova': typeof AuthenticatedFixasNovaRoute
  '/metas/nova': typeof AuthenticatedMetasNovaRoute
  '/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/cartoes': typeof AuthenticatedCartoesIndexRoute
  '/categorias': typeof AuthenticatedCategoriasIndexRoute
  '/fixas': typeof AuthenticatedFixasIndexRoute
  '/metas': typeof AuthenticatedMetasIndexRoute
  '/transacoes': typeof AuthenticatedTransacoesIndexRoute
  '/cartoes/$id/editar': typeof AuthenticatedCartoesIdEditarRoute
  '/categorias/$id/editar': typeof AuthenticatedCategoriasIdEditarRoute
  '/fixas/$id/editar': typeof AuthenticatedFixasIdEditarRoute
  '/metas/$id/editar': typeof AuthenticatedMetasIdEditarRoute
  '/transacoes/$id/editar': typeof AuthenticatedTransacoesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/senha-alterada': typeof SenhaAlteradaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRouteWithChildren
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRouteWithChildren
  '/_authenticated/conexoes': typeof AuthenticatedConexoesRoute
  '/_authenticated/fixas': typeof AuthenticatedFixasRouteWithChildren
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/transacoes': typeof AuthenticatedTransacoesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cartoes/novo': typeof AuthenticatedCartoesNovoRoute
  '/_authenticated/categorias/nova': typeof AuthenticatedCategoriasNovaRoute
  '/_authenticated/fixas/nova': typeof AuthenticatedFixasNovaRoute
  '/_authenticated/metas/nova': typeof AuthenticatedMetasNovaRoute
  '/_authenticated/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/_authenticated/cartoes/': typeof AuthenticatedCartoesIndexRoute
  '/_authenticated/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/_authenticated/fixas/': typeof AuthenticatedFixasIndexRoute
  '/_authenticated/metas/': typeof AuthenticatedMetasIndexRoute
  '/_authenticated/transacoes/': typeof AuthenticatedTransacoesIndexRoute
  '/_authenticated/cartoes/$id/editar': typeof AuthenticatedCartoesIdEditarRoute
  '/_authenticated/categorias/$id/editar': typeof AuthenticatedCategoriasIdEditarRoute
  '/_authenticated/fixas/$id/editar': typeof AuthenticatedFixasIdEditarRoute
  '/_authenticated/metas/$id/editar': typeof AuthenticatedMetasIdEditarRoute
  '/_authenticated/transacoes/$id/editar': typeof AuthenticatedTransacoesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/senha-alterada'
    | '/admin'
    | '/cartoes'
    | '/categorias'
    | '/conexoes'
    | '/fixas'
    | '/importar'
    | '/metas'
    | '/perfil'
    | '/transacoes'
    | '/auth/callback'
    | '/cartoes/novo'
    | '/categorias/nova'
    | '/fixas/nova'
    | '/metas/nova'
    | '/transacoes/novo'
    | '/cartoes/'
    | '/categorias/'
    | '/fixas/'
    | '/metas/'
    | '/transacoes/'
    | '/cartoes/$id/editar'
    | '/categorias/$id/editar'
    | '/fixas/$id/editar'
    | '/metas/$id/editar'
    | '/transacoes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/definir-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/senha-alterada'
    | '/admin'
    | '/conexoes'
    | '/importar'
    | '/perfil'
    | '/auth/callback'
    | '/'
    | '/cartoes/novo'
    | '/categorias/nova'
    | '/fixas/nova'
    | '/metas/nova'
    | '/transacoes/novo'
    | '/cartoes'
    | '/categorias'
    | '/fixas'
    | '/metas'
    | '/transacoes'
    | '/cartoes/$id/editar'
    | '/categorias/$id/editar'
    | '/fixas/$id/editar'
    | '/metas/$id/editar'
    | '/transacoes/$id/editar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/definir-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/senha-alterada'
    | '/_authenticated/admin'
    | '/_authenticated/cartoes'
    | '/_authenticated/categorias'
    | '/_authenticated/conexoes'
    | '/_authenticated/fixas'
    | '/_authenticated/importar'
    | '/_authenticated/metas'
    | '/_authenticated/perfil'
    | '/_authenticated/transacoes'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/cartoes/novo'
    | '/_authenticated/categorias/nova'
    | '/_authenticated/fixas/nova'
    | '/_authenticated/metas/nova'
    | '/_authenticated/transacoes/novo'
    | '/_authenticated/cartoes/'
    | '/_authenticated/categorias/'
    | '/_authenticated/fixas/'
    | '/_authenticated/metas/'
    | '/_authenticated/transacoes/'
    | '/_authenticated/cartoes/$id/editar'
    | '/_authenticated/categorias/$id/editar'
    | '/_authenticated/fixas/$id/editar'
    | '/_authenticated/metas/$id/editar'
    | '/_authenticated/transacoes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SenhaAlteradaRoute: typeof SenhaAlteradaRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senha-alterada': {
      id: '/senha-alterada'
      path: '/senha-alterada'
      fullPath: '/senha-alterada'
      preLoaderRoute: typeof SenhaAlteradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conexoes': {
      id: '/_authenticated/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof AuthenticatedConexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fixas': {
      id: '/_authenticated/fixas'
      path: '/fixas'
      fullPath: '/fixas'
      preLoaderRoute: typeof AuthenticatedFixasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacoes': {
      id: '/_authenticated/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AuthenticatedTransacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cartoes/': {
      id: '/_authenticated/cartoes/'
      path: '/'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof AuthenticatedCartoesIndexRouteImport
      parentRoute: typeof AuthenticatedCartoesRoute
    }
    '/_authenticated/cartoes/novo': {
      id: '/_authenticated/cartoes/novo'
      path: '/novo'
      fullPath: '/cartoes/novo'
      preLoaderRoute: typeof AuthenticatedCartoesNovoRouteImport
      parentRoute: typeof AuthenticatedCartoesRoute
    }
    '/_authenticated/categorias/': {
      id: '/_authenticated/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof AuthenticatedCategoriasIndexRouteImport
      parentRoute: typeof AuthenticatedCategoriasRoute
    }
    '/_authenticated/categorias/nova': {
      id: '/_authenticated/categorias/nova'
      path: '/nova'
      fullPath: '/categorias/nova'
      preLoaderRoute: typeof AuthenticatedCategoriasNovaRouteImport
      parentRoute: typeof AuthenticatedCategoriasRoute
    }
    '/_authenticated/fixas/': {
      id: '/_authenticated/fixas/'
      path: '/'
      fullPath: '/fixas/'
      preLoaderRoute: typeof AuthenticatedFixasIndexRouteImport
      parentRoute: typeof AuthenticatedFixasRoute
    }
    '/_authenticated/fixas/nova': {
      id: '/_authenticated/fixas/nova'
      path: '/nova'
      fullPath: '/fixas/nova'
      preLoaderRoute: typeof AuthenticatedFixasNovaRouteImport
      parentRoute: typeof AuthenticatedFixasRoute
    }
    '/_authenticated/metas/': {
      id: '/_authenticated/metas/'
      path: '/'
      fullPath: '/metas/'
      preLoaderRoute: typeof AuthenticatedMetasIndexRouteImport
      parentRoute: typeof AuthenticatedMetasRoute
    }
    '/_authenticated/metas/nova': {
      id: '/_authenticated/metas/nova'
      path: '/nova'
      fullPath: '/metas/nova'
      preLoaderRoute: typeof AuthenticatedMetasNovaRouteImport
      parentRoute: typeof AuthenticatedMetasRoute
    }
    '/_authenticated/transacoes/': {
      id: '/_authenticated/transacoes/'
      path: '/'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof AuthenticatedTransacoesIndexRouteImport
      parentRoute: typeof AuthenticatedTransacoesRoute
    }
    '/_authenticated/transacoes/novo': {
      id: '/_authenticated/transacoes/novo'
      path: '/novo'
      fullPath: '/transacoes/novo'
      preLoaderRoute: typeof AuthenticatedTransacoesNovoRouteImport
      parentRoute: typeof AuthenticatedTransacoesRoute
    }
    '/_authenticated/cartoes/$id/editar': {
      id: '/_authenticated/cartoes/$id/editar'
      path: '/$id/editar'
      fullPath: '/cartoes/$id/editar'
      preLoaderRoute: typeof AuthenticatedCartoesIdEditarRouteImport
      parentRoute: typeof AuthenticatedCartoesRoute
    }
    '/_authenticated/categorias/$id/editar': {
      id: '/_authenticated/categorias/$id/editar'
      path: '/$id/editar'
      fullPath: '/categorias/$id/editar'
      preLoaderRoute: typeof AuthenticatedCategoriasIdEditarRouteImport
      parentRoute: typeof AuthenticatedCategoriasRoute
    }
    '/_authenticated/fixas/$id/editar': {
      id: '/_authenticated/fixas/$id/editar'
      path: '/$id/editar'
      fullPath: '/fixas/$id/editar'
      preLoaderRoute: typeof AuthenticatedFixasIdEditarRouteImport
      parentRoute: typeof AuthenticatedFixasRoute
    }
    '/_authenticated/metas/$id/editar': {
      id: '/_authenticated/metas/$id/editar'
      path: '/$id/editar'
      fullPath: '/metas/$id/editar'
      preLoaderRoute: typeof AuthenticatedMetasIdEditarRouteImport
      parentRoute: typeof AuthenticatedMetasRoute
    }
    '/_authenticated/transacoes/$id/editar': {
      id: '/_authenticated/transacoes/$id/editar'
      path: '/$id/editar'
      fullPath: '/transacoes/$id/editar'
      preLoaderRoute: typeof AuthenticatedTransacoesIdEditarRouteImport
      parentRoute: typeof AuthenticatedTransacoesRoute
    }
  }
}

interface AuthenticatedCartoesRouteChildren {
  AuthenticatedCartoesNovoRoute: typeof AuthenticatedCartoesNovoRoute
  AuthenticatedCartoesIndexRoute: typeof AuthenticatedCartoesIndexRoute
  AuthenticatedCartoesIdEditarRoute: typeof AuthenticatedCartoesIdEditarRoute
}

const AuthenticatedCartoesRouteChildren: AuthenticatedCartoesRouteChildren = {
  AuthenticatedCartoesNovoRoute: AuthenticatedCartoesNovoRoute,
  AuthenticatedCartoesIndexRoute: AuthenticatedCartoesIndexRoute,
  AuthenticatedCartoesIdEditarRoute: AuthenticatedCartoesIdEditarRoute,
}

const AuthenticatedCartoesRouteWithChildren =
  AuthenticatedCartoesRoute._addFileChildren(AuthenticatedCartoesRouteChildren)

interface AuthenticatedCategoriasRouteChildren {
  AuthenticatedCategoriasNovaRoute: typeof AuthenticatedCategoriasNovaRoute
  AuthenticatedCategoriasIndexRoute: typeof AuthenticatedCategoriasIndexRoute
  AuthenticatedCategoriasIdEditarRoute: typeof AuthenticatedCategoriasIdEditarRoute
}

const AuthenticatedCategoriasRouteChildren: AuthenticatedCategoriasRouteChildren =
  {
    AuthenticatedCategoriasNovaRoute: AuthenticatedCategoriasNovaRoute,
    AuthenticatedCategoriasIndexRoute: AuthenticatedCategoriasIndexRoute,
    AuthenticatedCategoriasIdEditarRoute: AuthenticatedCategoriasIdEditarRoute,
  }

const AuthenticatedCategoriasRouteWithChildren =
  AuthenticatedCategoriasRoute._addFileChildren(
    AuthenticatedCategoriasRouteChildren,
  )

interface AuthenticatedFixasRouteChildren {
  AuthenticatedFixasNovaRoute: typeof AuthenticatedFixasNovaRoute
  AuthenticatedFixasIndexRoute: typeof AuthenticatedFixasIndexRoute
  AuthenticatedFixasIdEditarRoute: typeof AuthenticatedFixasIdEditarRoute
}

const AuthenticatedFixasRouteChildren: AuthenticatedFixasRouteChildren = {
  AuthenticatedFixasNovaRoute: AuthenticatedFixasNovaRoute,
  AuthenticatedFixasIndexRoute: AuthenticatedFixasIndexRoute,
  AuthenticatedFixasIdEditarRoute: AuthenticatedFixasIdEditarRoute,
}

const AuthenticatedFixasRouteWithChildren =
  AuthenticatedFixasRoute._addFileChildren(AuthenticatedFixasRouteChildren)

interface AuthenticatedMetasRouteChildren {
  AuthenticatedMetasNovaRoute: typeof AuthenticatedMetasNovaRoute
  AuthenticatedMetasIndexRoute: typeof AuthenticatedMetasIndexRoute
  AuthenticatedMetasIdEditarRoute: typeof AuthenticatedMetasIdEditarRoute
}

const AuthenticatedMetasRouteChildren: AuthenticatedMetasRouteChildren = {
  AuthenticatedMetasNovaRoute: AuthenticatedMetasNovaRoute,
  AuthenticatedMetasIndexRoute: AuthenticatedMetasIndexRoute,
  AuthenticatedMetasIdEditarRoute: AuthenticatedMetasIdEditarRoute,
}

const AuthenticatedMetasRouteWithChildren =
  AuthenticatedMetasRoute._addFileChildren(AuthenticatedMetasRouteChildren)

interface AuthenticatedTransacoesRouteChildren {
  AuthenticatedTransacoesNovoRoute: typeof AuthenticatedTransacoesNovoRoute
  AuthenticatedTransacoesIndexRoute: typeof AuthenticatedTransacoesIndexRoute
  AuthenticatedTransacoesIdEditarRoute: typeof AuthenticatedTransacoesIdEditarRoute
}

const AuthenticatedTransacoesRouteChildren: AuthenticatedTransacoesRouteChildren =
  {
    AuthenticatedTransacoesNovoRoute: AuthenticatedTransacoesNovoRoute,
    AuthenticatedTransacoesIndexRoute: AuthenticatedTransacoesIndexRoute,
    AuthenticatedTransacoesIdEditarRoute: AuthenticatedTransacoesIdEditarRoute,
  }

const AuthenticatedTransacoesRouteWithChildren =
  AuthenticatedTransacoesRoute._addFileChildren(
    AuthenticatedTransacoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRouteWithChildren
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRouteWithChildren
  AuthenticatedConexoesRoute: typeof AuthenticatedConexoesRoute
  AuthenticatedFixasRoute: typeof AuthenticatedFixasRouteWithChildren
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTransacoesRoute: typeof AuthenticatedTransacoesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCartoesRoute: AuthenticatedCartoesRouteWithChildren,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRouteWithChildren,
  AuthenticatedConexoesRoute: AuthenticatedConexoesRoute,
  AuthenticatedFixasRoute: AuthenticatedFixasRouteWithChildren,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTransacoesRoute: AuthenticatedTransacoesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SenhaAlteradaRoute: SenhaAlteradaRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
